import { MenuItem } from '../types/menu'
import { withMenuImages } from '../lib/menuImages'
import { STATIC_LOCATION_IDS } from './staticLocations'

type StaticItem = Omit<MenuItem, 'createdAt' | 'updatedAt'>
type MenuItemInput = Omit<StaticItem, 'imageURL' | 'rating' | 'reviewCount' | 'isHalal' | 'isAvailable' | 'locationIds'>

const LOC = STATIC_LOCATION_IDS

function item(partial: MenuItemInput): StaticItem {
  return {
    imageURL: '',
    rating: 0,
    reviewCount: 0,
    isHalal: true,
    isAvailable: true,
    locationIds: [...LOC],
    ...partial,
  }
}

const RAW_MENU: StaticItem[] = [
  // ── BIRYANI / NAWABI RICE SPECIALS ─────────────────────────────────
  item({ id:'veg-dum-biryani', name:'Vegetable Dum Biryani', description:'Aromatic basmati rice cooked with assorted vegetables and traditional Hyderabadi spices, accompanied by raita.', price:1199, category:'biryani', subcategory:'veg', isVegetarian:true, isSpicy:false, spiceLevel:1, allergens:['dairy'], tags:[], isBuffetItem:true }),
  item({ id:'egg-biryani', name:'Egg Biryani', description:'Boiled eggs cooked in a flavorful Hyderabadi-style sauce and mixed with basmati rice, served with raita.', price:1299, category:'biryani', subcategory:'non-veg', isVegetarian:false, isSpicy:false, spiceLevel:1, allergens:['eggs','dairy'], tags:[], isBuffetItem:true }),
  item({ id:'hyderabadi-chicken-dum-biryani', name:'Hyderabadi Chicken Dum Biryani', description:'Tender chicken pieces marinated in homemade spices and cooked with basmati rice, flavored with traditional Hyderabadi spices.', price:1499, category:'biryani', subcategory:'non-veg', isVegetarian:false, isSpicy:false, spiceLevel:2, allergens:['dairy'], tags:['bestseller','signature'], isBuffetItem:true }),
  item({ id:'paneer-dum-biryani', name:'Paneer Dum Biryani', description:'Spicy cubes of cottage cheese marinated in Hyderabadi-style sauce and cooked with basmati rice.', price:1499, category:'biryani', subcategory:'veg', isVegetarian:true, isSpicy:false, spiceLevel:1, allergens:['dairy'], tags:[], isBuffetItem:true }),
  item({ id:'boneless-chicken-dum-biryani', name:'Boneless Chicken Dum Biryani', description:'Boneless chicken pieces cooked with traditional Hyderabadi spices and basmati rice.', price:1599, category:'biryani', subcategory:'non-veg', isVegetarian:false, isSpicy:false, spiceLevel:2, allergens:['dairy'], tags:['bestseller'], isBuffetItem:false }),
  item({ id:'chicken-65-biryani', name:'Chicken 65 Biryani', description:'Chicken 65 sautéed with basmati rice and Indian spices, served with raita.', price:1699, category:'biryani', subcategory:'non-veg', isVegetarian:false, isSpicy:true, spiceLevel:2, allergens:['eggs','dairy'], tags:['bestseller'], isBuffetItem:false }),
  item({ id:'hyderabadi-goat-dum-biryani', name:'Hyderabadi Goat Dum Biryani', description:'Tender pieces of goat cooked with traditional Hyderabadi spices and basmati rice.', price:1999, category:'biryani', subcategory:'non-veg', isVegetarian:false, isSpicy:false, spiceLevel:2, allergens:['dairy'], tags:['signature','bestseller'], isBuffetItem:false }),

  // ── VEG APPETIZERS ─────────────────────────────────────────────────
  item({ id:'veg-samosa', name:'Veg Samosa (2 Pieces)', description:'Crispy fried filo pastry triangles filled with spiced potatoes, peas, and vegetables, a classic Indian appetizer.', price:499, category:'veg-appetizers', subcategory:'veg', isVegetarian:true, isSpicy:false, spiceLevel:1, allergens:['gluten'], tags:['bestseller'], isBuffetItem:true }),
  item({ id:'veg-pakora', name:'Veg Pakora', description:'Assorted vegetables coated in a crispy gram flour batter, seasoned with aromatic spices and herbs.', price:599, category:'veg-appetizers', subcategory:'veg', isVegetarian:true, isSpicy:false, spiceLevel:1, allergens:['gluten'], tags:[], isBuffetItem:true }),
  item({ id:'onion-palak-pakora', name:'Onion & Palak Pakora', description:'Crispy fritters of onion and spinach in spiced gram flour batter.', price:699, category:'veg-appetizers', subcategory:'veg', isVegetarian:true, isSpicy:false, spiceLevel:1, allergens:['gluten'], tags:[], isBuffetItem:true }),
  item({ id:'french-fries', name:'French Fries', description:'Golden crispy fries, lightly seasoned.', price:499, category:'veg-appetizers', subcategory:'veg', isVegetarian:true, isSpicy:false, spiceLevel:1, allergens:[], tags:[], isBuffetItem:true }),
  item({ id:'onion-bhajee', name:'Onion Bhajee', description:'Thinly sliced onions coated in a spiced batter and fried until golden and crispy, a popular and flavorful appetizer.', price:599, category:'veg-appetizers', subcategory:'veg', isVegetarian:true, isSpicy:false, spiceLevel:1, allergens:['gluten'], tags:[], isBuffetItem:false }),
  item({ id:'samosa-chaat', name:'Samosa Chaat', description:'Samosas are smashed and broken, and served with whole chana masala and sweet, spicy, tangy, and crispy toppings.', price:999, category:'veg-appetizers', subcategory:'veg', isVegetarian:true, isSpicy:true, spiceLevel:2, allergens:['gluten'], tags:['bestseller'], isBuffetItem:true }),
  item({ id:'mix-veg-appetizer', name:'Mix Veg. Appetizer', description:'Taste the mixture of Veg Samosa, Veg Pakora and Onion Bhajee.', price:1099, category:'veg-appetizers', subcategory:'veg', isVegetarian:true, isSpicy:false, spiceLevel:1, allergens:['gluten'], tags:[], isBuffetItem:false }),
  item({ id:'gobi-manchurian', name:'Gobi Manchurian', description:'Cauliflower florets battered and fried, then sautéed in a spicy-sweet sauce made with soy, vinegar, chili, ginger and garlic.', price:1199, category:'veg-appetizers', subcategory:'veg', isVegetarian:true, isSpicy:true, spiceLevel:2, allergens:['gluten','soy'], tags:[], isBuffetItem:false }),
  item({ id:'chilli-gobi', name:'Chili Gobi', description:'Lightly battered cauliflower florets sautéed in a spicy chili sauce, a perfect combination of heat and flavor.', price:1199, category:'veg-appetizers', subcategory:'veg', isVegetarian:true, isSpicy:true, spiceLevel:3, allergens:['gluten'], tags:[], isBuffetItem:false }),
  item({ id:'gobi-65', name:'Gobi 65', description:"Crispy and spicy cauliflower florets sautéed with our chef's special 65 sauce.", price:1199, category:'veg-appetizers', subcategory:'veg', isVegetarian:true, isSpicy:true, spiceLevel:2, allergens:['gluten'], tags:[], isBuffetItem:false }),
  item({ id:'chilli-paneer', name:'Chilli Paneer', description:'Soft and succulent Indian cottage cheese cubes sautéed in a spicy chili sauce.', price:1199, category:'veg-appetizers', subcategory:'veg', isVegetarian:true, isSpicy:true, spiceLevel:2, allergens:['dairy'], tags:[], isBuffetItem:false }),
  item({ id:'paneer-manchurian', name:'Paneer Manchurian', description:'Indian cottage cheese cubes sautéed in a tangy-sweet Manchurian sauce.', price:1299, category:'veg-appetizers', subcategory:'veg', isVegetarian:true, isSpicy:false, spiceLevel:1, allergens:['dairy','gluten'], tags:[], isBuffetItem:false }),
  item({ id:'paneer-65', name:'Paneer 65', description:"Soft and creamy Indian cottage cheese cubes sautéed with our chef's special 65 sauce.", price:1299, category:'veg-appetizers', subcategory:'veg', isVegetarian:true, isSpicy:true, spiceLevel:2, allergens:['dairy'], tags:[], isBuffetItem:false }),
  item({ id:'paneer-pakora', name:'Paneer Pakora', description:'Soft and crispy Indian cottage cheese cubes flavored with ground spices, coated in a chickpea flour batter and deep-fried.', price:1299, category:'veg-appetizers', subcategory:'veg', isVegetarian:true, isSpicy:false, spiceLevel:1, allergens:['dairy','gluten'], tags:[], isBuffetItem:false }),

  // ── NON-VEG APPETIZERS ─────────────────────────────────────────────
  item({ id:'chicken-pakora', name:'Chicken Pakora', description:'Quick Indian appetizer made with gram flour, chicken and a blend of spices and herbs.', price:1499, category:'non-veg-appetizers', subcategory:'non-veg', isVegetarian:false, isSpicy:true, spiceLevel:2, allergens:['gluten'], tags:['bestseller'], isBuffetItem:true }),
  item({ id:'chicken-nuggets', name:'Chicken Nuggets', description:'Crispy breaded chicken bites served hot.', price:999, category:'non-veg-appetizers', subcategory:'non-veg', isVegetarian:false, isSpicy:false, spiceLevel:1, allergens:['gluten'], tags:[], isBuffetItem:true }),
  item({ id:'fish-pakora', name:'Fish Pakora', description:'Quick Indian appetizer made with gram flour, fish and a blend of spices and herbs.', price:1699, category:'non-veg-appetizers', subcategory:'non-veg', isVegetarian:false, isSpicy:true, spiceLevel:2, allergens:['gluten'], tags:[], isBuffetItem:false }),
  item({ id:'shrimp-pakora', name:'Shrimp Pakora', description:'Quick Indian appetizer made with gram flour, shrimp and a blend of spices and herbs.', price:1699, category:'non-veg-appetizers', subcategory:'non-veg', isVegetarian:false, isSpicy:true, spiceLevel:2, allergens:['gluten','shellfish'], tags:[], isBuffetItem:false }),
  item({ id:'chicken-65', name:'Chicken 65', description:'Chicken coated in spicy masala marinade, deep fried and tossed in house-made spices.', price:1499, category:'non-veg-appetizers', subcategory:'non-veg', isVegetarian:false, isSpicy:true, spiceLevel:3, allergens:['eggs','gluten'], tags:['bestseller'], isBuffetItem:true }),
  item({ id:'fish-65', name:'Fish 65', description:'Fish coated in spicy masala marinade, deep fried and tossed in house-made spices.', price:1699, category:'non-veg-appetizers', subcategory:'non-veg', isVegetarian:false, isSpicy:true, spiceLevel:3, allergens:['eggs','gluten'], tags:[], isBuffetItem:false }),
  item({ id:'shrimp-65', name:'Shrimp 65', description:'Shrimp coated in spicy masala marinade, deep fried and tossed in house-made spices.', price:1699, category:'non-veg-appetizers', subcategory:'non-veg', isVegetarian:false, isSpicy:true, spiceLevel:3, allergens:['eggs','gluten','shellfish'], tags:[], isBuffetItem:false }),
  item({ id:'chicken-manchurian', name:'Chicken Manchurian', description:'Delicious fried chicken in slightly sweet and sour Manchurian sauce.', price:1499, category:'non-veg-appetizers', subcategory:'non-veg', isVegetarian:false, isSpicy:true, spiceLevel:2, allergens:['gluten','soy'], tags:[], isBuffetItem:false }),
  item({ id:'fish-manchurian', name:'Fish Manchurian', description:'Delicious fried fish in slightly sweet and sour Manchurian sauce.', price:1699, category:'non-veg-appetizers', subcategory:'non-veg', isVegetarian:false, isSpicy:true, spiceLevel:2, allergens:['gluten','soy'], tags:[], isBuffetItem:false }),
  item({ id:'shrimp-manchurian', name:'Shrimp Manchurian', description:'Delicious fried shrimp in slightly sweet and sour Manchurian sauce.', price:1699, category:'non-veg-appetizers', subcategory:'non-veg', isVegetarian:false, isSpicy:true, spiceLevel:2, allergens:['gluten','soy','shellfish'], tags:[], isBuffetItem:false }),
  item({ id:'chilli-chicken', name:'Chilli Chicken', description:'Spicy and flavorful chicken made with chicken marinated in Chinese sauces, fried and tossed with peppers and onions.', price:1499, category:'non-veg-appetizers', subcategory:'non-veg', isVegetarian:false, isSpicy:true, spiceLevel:3, allergens:['gluten','soy'], tags:[], isBuffetItem:false }),
  item({ id:'fish-chilli', name:'Chilli Fish', description:'Spicy and flavorful fish made with fish marinated in Chinese sauces, fried and tossed with peppers and onions.', price:1699, category:'non-veg-appetizers', subcategory:'non-veg', isVegetarian:false, isSpicy:true, spiceLevel:3, allergens:['gluten','soy'], tags:[], isBuffetItem:false }),
  item({ id:'shrimp-chilli', name:'Chilli Shrimp', description:'Spicy and flavorful shrimp made with shrimp marinated in Chinese sauces, fried and tossed with peppers and onions.', price:1699, category:'non-veg-appetizers', subcategory:'non-veg', isVegetarian:false, isSpicy:true, spiceLevel:3, allergens:['gluten','soy','shellfish'], tags:[], isBuffetItem:false }),
  item({ id:'chicken-lollipop', name:'Chicken Lollipop', description:'Chicken lollipop is a popular Indo-Chinese appetizer where a frenched chicken drumette is marinated and battered.', price:1499, category:'non-veg-appetizers', subcategory:'non-veg', isVegetarian:false, isSpicy:true, spiceLevel:2, allergens:['gluten'], tags:['bestseller'], isBuffetItem:false }),
  item({ id:'fish-lollipop', name:'Fish Lollipop', description:'Popular Indo-Chinese style fish appetizer, marinated and battered.', price:1699, category:'non-veg-appetizers', subcategory:'non-veg', isVegetarian:false, isSpicy:true, spiceLevel:2, allergens:['gluten'], tags:[], isBuffetItem:false }),
  item({ id:'shrimp-lollipop', name:'Shrimp Lollipop', description:'Popular Indo-Chinese style shrimp appetizer, marinated and battered.', price:1699, category:'non-veg-appetizers', subcategory:'non-veg', isVegetarian:false, isSpicy:true, spiceLevel:2, allergens:['gluten','shellfish'], tags:[], isBuffetItem:false }),
  item({ id:'chicken-majestic', name:'Chicken Majestic', description:'Famous Hyderabadi chicken appetizer with thick yogurt-based sauce and curry leaves.', price:1499, category:'non-veg-appetizers', subcategory:'non-veg', isVegetarian:false, isSpicy:true, spiceLevel:2, allergens:['dairy'], tags:[], isBuffetItem:false }),
  item({ id:'fish-majestic', name:'Fish Majestic', description:'Hyderabadi-style fish appetizer with thick yogurt-based sauce and curry leaves.', price:1699, category:'non-veg-appetizers', subcategory:'non-veg', isVegetarian:false, isSpicy:true, spiceLevel:2, allergens:['dairy'], tags:[], isBuffetItem:false }),
  item({ id:'shrimp-majestic', name:'Shrimp Majestic', description:'Hyderabadi-style shrimp appetizer with thick yogurt-based sauce and curry leaves.', price:1699, category:'non-veg-appetizers', subcategory:'non-veg', isVegetarian:false, isSpicy:true, spiceLevel:2, allergens:['dairy','shellfish'], tags:[], isBuffetItem:false }),
  item({ id:'talawa-gosht', name:'Talawa Gosht (Goat Meat Fry)', description:'Marinated bone-in goat pieces sautéed in a spicy special 65 sauce.', price:1999, category:'non-veg-appetizers', subcategory:'non-veg', isVegetarian:false, isSpicy:true, spiceLevel:2, allergens:[], tags:['signature'], isBuffetItem:false }),

  // ── VEG CURRIES ────────────────────────────────────────────────────
  item({ id:'mixed-vegetable-curry', name:'Mixed Vegetable Curry', description:'A delicious mix of vegetables cooked in a traditional Indian onion-tomato gravy.', price:1299, category:'veg-curries', subcategory:'veg', isVegetarian:true, isSpicy:false, spiceLevel:1, allergens:[], tags:[], isBuffetItem:true }),
  item({ id:'chana-masala', name:'Chana Masala', description:'Tender chickpeas in a rich tomato-based sauce with authentic Indian spices.', price:1299, category:'veg-curries', subcategory:'veg', isVegetarian:true, isSpicy:false, spiceLevel:1, allergens:[], tags:[], isBuffetItem:true }),
  item({ id:'tarka-dal', name:'Tarka Dal', description:'A smooth and creamy lentil dish tempered with aromatic spices and curry leaves.', price:1299, category:'veg-curries', subcategory:'veg', isVegetarian:true, isSpicy:false, spiceLevel:1, allergens:[], tags:[], isBuffetItem:true }),
  item({ id:'white-rice', name:'White Rice', description:'Steamed basmati rice.', price:399, category:'veg-curries', subcategory:'veg', isVegetarian:true, isSpicy:false, spiceLevel:1, allergens:[], tags:[], isBuffetItem:true }),
  item({ id:'bhindi-masala', name:'Bhindi Masala', description:'Okra cooked with onions, tomatoes and aromatic spices.', price:1299, category:'veg-curries', subcategory:'veg', isVegetarian:true, isSpicy:false, spiceLevel:1, allergens:[], tags:[], isBuffetItem:true }),
  item({ id:'saag-dal', name:'Saag Dal', description:'Spinach and split pea stew bursting with flavors.', price:1299, category:'veg-curries', subcategory:'veg', isVegetarian:true, isSpicy:false, spiceLevel:1, allergens:[], tags:[], isBuffetItem:true }),
  item({ id:'aloo-gobi', name:'Aloo Gobi', description:'Potatoes and cauliflower cooked in traditional Indian spices.', price:1299, category:'veg-curries', subcategory:'veg', isVegetarian:true, isSpicy:false, spiceLevel:1, allergens:[], tags:[], isBuffetItem:true }),
  item({ id:'saag-palak-paneer', name:'Saag / Palak Paneer', description:'Spinach cooked with Indian cottage cheese.', price:1399, category:'veg-curries', subcategory:'veg', isVegetarian:true, isSpicy:false, spiceLevel:1, allergens:['dairy'], tags:[], isBuffetItem:true }),
  item({ id:'paneer-karahi', name:'Paneer Karahi', description:'Paneer, onions and green bell peppers cooked in a spicy onion-tomato-based gravy.', price:1399, category:'veg-curries', subcategory:'veg', isVegetarian:true, isSpicy:true, spiceLevel:2, allergens:['dairy'], tags:[], isBuffetItem:true }),
  item({ id:'paneer-khurma', name:'Paneer Khurma', description:'A creamy, rich and delicately flavored curry made with paneer, almonds, onions, yogurt and spices.', price:1399, category:'veg-curries', subcategory:'veg', isVegetarian:true, isSpicy:false, spiceLevel:1, allergens:['dairy','nuts'], tags:[], isBuffetItem:true }),
  item({ id:'matar-paneer', name:'Matar Paneer', description:'A delicious combination of soft paneer and green peas in a rich tomato-based gravy.', price:1399, category:'veg-curries', subcategory:'veg', isVegetarian:true, isSpicy:false, spiceLevel:1, allergens:['dairy'], tags:[], isBuffetItem:true }),
  item({ id:'vegetable-khurma', name:'Vegetable Khurma', description:'Mixed vegetables cooked in a rich and creamy coconut-based gravy.', price:1399, category:'veg-curries', subcategory:'veg', isVegetarian:true, isSpicy:false, spiceLevel:1, allergens:['nuts'], tags:[], isBuffetItem:true }),
  item({ id:'vegetable-masala', name:'Vegetable Masala', description:'Vegetables cooked in onion and tomato gravy with aromatic spices.', price:1399, category:'veg-curries', subcategory:'veg', isVegetarian:true, isSpicy:false, spiceLevel:1, allergens:[], tags:[], isBuffetItem:true }),
  item({ id:'mix-veg-curry', name:'Mix Veg Curry', description:'A variety of vegetables cooked in a creamy coconut curry.', price:1399, category:'veg-curries', subcategory:'veg', isVegetarian:true, isSpicy:false, spiceLevel:1, allergens:[], tags:[], isBuffetItem:true }),
  item({ id:'paneer-tikka-masala', name:'Paneer Tikka Masala', description:'Paneer cubes cooked in a rich tomato-based sauce, served with biryani rice.', price:1499, category:'veg-curries', subcategory:'veg', isVegetarian:true, isSpicy:false, spiceLevel:1, allergens:['dairy'], tags:['bestseller'], isBuffetItem:true }),

  // ── NON-VEG CURRIES ────────────────────────────────────────────────
  item({ id:'butter-chicken', name:'Butter Chicken', description:"Butter Chicken also known as Chicken Makhani is a classic Indian dish that's made by simmering marinated or grilled chicken in a spicy, aromatic, buttery and creamy tomato onion gravy.", price:1599, category:'non-veg-curries', subcategory:'non-veg', isVegetarian:false, isSpicy:false, spiceLevel:1, allergens:['dairy'], tags:['bestseller','signature'], isBuffetItem:true }),
  item({ id:'chicken-tikka-masala', name:'Chicken Tikka Masala', description:'Tikka masala is a dish consisting of roasted marinated chicken chunks in a spiced sauce. The sauce is buttery creamy and orange-coloured.', price:1699, category:'non-veg-curries', subcategory:'non-veg', isVegetarian:false, isSpicy:false, spiceLevel:1, allergens:['dairy'], tags:['bestseller'], isBuffetItem:true }),
  item({ id:'lamb-tikka-masala', name:'Lamb/Goat Tikka Masala', description:'Tikka masala with roasted marinated lamb or goat in a buttery, creamy spiced sauce.', price:1999, category:'non-veg-curries', subcategory:'non-veg', isVegetarian:false, isSpicy:false, spiceLevel:1, allergens:['dairy'], tags:[], isBuffetItem:false }),
  item({ id:'shrimp-tikka-masala', name:'Shrimp Tikka Masala', description:'Tikka masala with shrimp in a buttery, creamy spiced sauce.', price:1999, category:'non-veg-curries', subcategory:'non-veg', isVegetarian:false, isSpicy:false, spiceLevel:1, allergens:['dairy','shellfish'], tags:[], isBuffetItem:false }),
  item({ id:'fish-tikka-masala', name:'Fish Tikka Masala', description:'Tikka masala with fish in a buttery, creamy spiced sauce.', price:1999, category:'non-veg-curries', subcategory:'non-veg', isVegetarian:false, isSpicy:false, spiceLevel:1, allergens:['dairy'], tags:[], isBuffetItem:false }),
  item({ id:'chicken-karahi', name:'Chicken Karahi', description:'The dish typically consists of a base of onions, garlic, ginger and spices being fried together to form a thick coating sauce.', price:1699, category:'non-veg-curries', subcategory:'non-veg', isVegetarian:false, isSpicy:true, spiceLevel:2, allergens:[], tags:[], isBuffetItem:true }),
  item({ id:'lamb-karahi', name:'Lamb/Goat Karahi', description:'Lamb or goat cooked in a karahi with onions, garlic, ginger and spices.', price:1999, category:'non-veg-curries', subcategory:'non-veg', isVegetarian:false, isSpicy:true, spiceLevel:2, allergens:[], tags:[], isBuffetItem:false }),
  item({ id:'shrimp-karahi', name:'Shrimp Karahi', description:'Shrimp cooked in a karahi with onions, garlic, ginger and spices.', price:1999, category:'non-veg-curries', subcategory:'non-veg', isVegetarian:false, isSpicy:true, spiceLevel:2, allergens:['shellfish'], tags:[], isBuffetItem:false }),
  item({ id:'fish-karahi', name:'Fish Karahi', description:'Fish cooked in a karahi with onions, garlic, ginger and spices.', price:1999, category:'non-veg-curries', subcategory:'non-veg', isVegetarian:false, isSpicy:true, spiceLevel:2, allergens:[], tags:[], isBuffetItem:false }),
  item({ id:'chicken-achari', name:'Chicken Achari', description:'Curry made with ingredients used to make achar or South Asian pickle giving it a tangy and spicy flavor.', price:1699, category:'non-veg-curries', subcategory:'non-veg', isVegetarian:false, isSpicy:true, spiceLevel:2, allergens:[], tags:['signature'], isBuffetItem:false }),
  item({ id:'lamb-achari', name:'Lamb/Goat Achari', description:'Pickle-spiced lamb or goat curry with a tangy and spicy flavor.', price:1999, category:'non-veg-curries', subcategory:'non-veg', isVegetarian:false, isSpicy:true, spiceLevel:2, allergens:[], tags:[], isBuffetItem:false }),
  item({ id:'shrimp-achari', name:'Shrimp Achari', description:'Pickle-spiced shrimp curry with a tangy and spicy flavor.', price:1999, category:'non-veg-curries', subcategory:'non-veg', isVegetarian:false, isSpicy:true, spiceLevel:2, allergens:['shellfish'], tags:[], isBuffetItem:false }),
  item({ id:'fish-achari', name:'Fish Achari', description:'Pickle-spiced fish curry with a tangy and spicy flavor.', price:1999, category:'non-veg-curries', subcategory:'non-veg', isVegetarian:false, isSpicy:true, spiceLevel:2, allergens:[], tags:[], isBuffetItem:false }),
  item({ id:'chicken-saag', name:'Chicken Saag / Palak', description:'Saag is a popular Indian dish consisting of meat in a smooth, creamy and delicious spinach gravy.', price:1699, category:'non-veg-curries', subcategory:'non-veg', isVegetarian:false, isSpicy:false, spiceLevel:1, allergens:['dairy'], tags:[], isBuffetItem:true }),
  item({ id:'lamb-saag', name:'Lamb/Goat Saag / Palak', description:'Lamb or goat in a smooth, creamy spinach gravy.', price:1999, category:'non-veg-curries', subcategory:'non-veg', isVegetarian:false, isSpicy:false, spiceLevel:1, allergens:['dairy'], tags:[], isBuffetItem:false }),
  item({ id:'shrimp-saag', name:'Shrimp Saag / Palak', description:'Shrimp in a smooth, creamy spinach gravy.', price:1999, category:'non-veg-curries', subcategory:'non-veg', isVegetarian:false, isSpicy:false, spiceLevel:1, allergens:['dairy','shellfish'], tags:[], isBuffetItem:false }),
  item({ id:'fish-saag', name:'Fish Saag / Palak', description:'Fish in a smooth, creamy spinach gravy.', price:1999, category:'non-veg-curries', subcategory:'non-veg', isVegetarian:false, isSpicy:false, spiceLevel:1, allergens:['dairy'], tags:[], isBuffetItem:false }),
  item({ id:'chicken-bhuna', name:'Chicken Bhuna', description:'The dish typically consists of a base of onions, garlic and spices being fried together to form a thick coating sauce.', price:1699, category:'non-veg-curries', subcategory:'non-veg', isVegetarian:false, isSpicy:true, spiceLevel:2, allergens:[], tags:[], isBuffetItem:false }),
  item({ id:'lamb-bhuna', name:'Lamb/Goat Bhuna', description:'Lamb or goat bhuna with onions, garlic and spices in a thick sauce.', price:1999, category:'non-veg-curries', subcategory:'non-veg', isVegetarian:false, isSpicy:true, spiceLevel:2, allergens:[], tags:[], isBuffetItem:false }),
  item({ id:'shrimp-bhuna', name:'Shrimp Bhuna', description:'Shrimp bhuna with onions, garlic and spices in a thick sauce.', price:1999, category:'non-veg-curries', subcategory:'non-veg', isVegetarian:false, isSpicy:true, spiceLevel:2, allergens:['shellfish'], tags:[], isBuffetItem:false }),
  item({ id:'fish-bhuna', name:'Fish Bhuna', description:'Fish bhuna with onions, garlic and spices in a thick sauce.', price:1999, category:'non-veg-curries', subcategory:'non-veg', isVegetarian:false, isSpicy:true, spiceLevel:2, allergens:[], tags:[], isBuffetItem:false }),
  item({ id:'chicken-vindaloo', name:'Chicken Vindaloo', description:"Vindaloo is a popular Indian curry originating from the Goa region. It's a hot, fiery and tangy dish made with meat, vegetables and plenty of spices.", price:1699, category:'non-veg-curries', subcategory:'non-veg', isVegetarian:false, isSpicy:true, spiceLevel:3, allergens:[], tags:[], isBuffetItem:false }),
  item({ id:'lamb-vindaloo', name:'Lamb/Goat Vindaloo', description:'Hot, fiery and tangy Goan-style vindaloo with lamb or goat.', price:1999, category:'non-veg-curries', subcategory:'non-veg', isVegetarian:false, isSpicy:true, spiceLevel:3, allergens:[], tags:[], isBuffetItem:false }),
  item({ id:'shrimp-vindaloo', name:'Shrimp Vindaloo', description:'Hot, fiery and tangy Goan-style vindaloo with shrimp.', price:1999, category:'non-veg-curries', subcategory:'non-veg', isVegetarian:false, isSpicy:true, spiceLevel:3, allergens:['shellfish'], tags:[], isBuffetItem:false }),
  item({ id:'fish-vindaloo', name:'Fish Vindaloo', description:'Hot, fiery and tangy Goan-style vindaloo with fish.', price:1999, category:'non-veg-curries', subcategory:'non-veg', isVegetarian:false, isSpicy:true, spiceLevel:3, allergens:[], tags:[], isBuffetItem:false }),

  // ── SIZZLERS ───────────────────────────────────────────────────────
  item({ id:'chicken-tandoori', name:'Chicken Tandoori', description:'Tender chicken pieces marinated in yogurt and spices, then roasted in a clay oven to perfection. Served sizzling hot with onions and lemon.', price:1499, category:'sizzlers', subcategory:'non-veg', isVegetarian:false, isSpicy:false, spiceLevel:1, allergens:['dairy'], tags:['bestseller'], isBuffetItem:true }),
  item({ id:'chicken-tangdi-kabab', name:'Chicken Tangdi Kabab', description:'Chicken drumsticks marinated in a spiced green herb and gram flour (besan) marinade and oven-grilled.', price:1799, category:'sizzlers', subcategory:'non-veg', isVegetarian:false, isSpicy:false, spiceLevel:1, allergens:['gluten','dairy'], tags:[], isBuffetItem:false }),
  item({ id:'chicken-tikka', name:'Chicken Tikka', description:'Boneless chicken marinated in a blend of yogurt and traditional Hyderabadi spices, then roasted over hot coals. Served sizzling hot with onions and lemon.', price:1499, category:'sizzlers', subcategory:'non-veg', isVegetarian:false, isSpicy:false, spiceLevel:1, allergens:['dairy'], tags:['bestseller'], isBuffetItem:false }),
  item({ id:'chicken-reshmi-kabab', name:'Chicken Reshmi Kabab', description:'Made with boneless chicken, cooked by marinating chunks of meat in curd, cream and paste, spices and then grilled in the Tandoor.', price:1799, category:'sizzlers', subcategory:'non-veg', isVegetarian:false, isSpicy:false, spiceLevel:1, allergens:['dairy','nuts'], tags:[], isBuffetItem:false }),
  item({ id:'tiranga-kabab', name:'Tiranga Kabab', description:'Mix of Chicken Hariyali, Malai and Red Chicken.', price:1799, category:'sizzlers', subcategory:'non-veg', isVegetarian:false, isSpicy:false, spiceLevel:1, allergens:['dairy'], tags:[], isBuffetItem:false }),
  item({ id:'paneer-tandoori', name:'Paneer Tandoori', description:'Cubes of cottage cheese marinated in a spicy yogurt mixture and then grilled to perfection in the Tandoor. Served sizzling hot with onions and lemon.', price:1699, category:'sizzlers', subcategory:'veg', isVegetarian:true, isSpicy:false, spiceLevel:1, allergens:['dairy'], tags:[], isBuffetItem:false }),
  item({ id:'mutton-reshmi-kabab', name:'Mutton Reshmi Kabab', description:'Made with boneless Lamb/Goat, cooked by marinating chunks of meat in curd, cream, cashew nut paste, spices and then grilled.', price:1999, category:'sizzlers', subcategory:'non-veg', isVegetarian:false, isSpicy:false, spiceLevel:1, allergens:['dairy','nuts'], tags:[], isBuffetItem:false }),
  item({ id:'fish-tandoori', name:'Fish Tandoori', description:'Fresh fish marinated in a tangy Tandoori spice blend, then grilled to flaky perfection in a clay Tandoor. Served sizzling hot with onions and lemon.', price:1999, category:'sizzlers', subcategory:'non-veg', isVegetarian:false, isSpicy:false, spiceLevel:1, allergens:[], tags:[], isBuffetItem:false }),
  item({ id:'mixed-tandoori-grill', name:'Mixed Tandoori Grill', description:"Can't decide? Try a combination of Tandoori chicken, tikka and seekh kabab served sizzling hot with onions and lemon.", price:1999, category:'sizzlers', subcategory:'non-veg', isVegetarian:false, isSpicy:false, spiceLevel:1, allergens:['dairy','gluten'], tags:['bestseller'], isBuffetItem:false }),
  item({ id:'shrimp-tandoori', name:'Shrimp Tandoori', description:'Jumbo shrimp marinated in a blend of yogurt and Indian spices, then grilled to perfection in the Tandoor. Served sizzling hot with onions and lemon.', price:1999, category:'sizzlers', subcategory:'non-veg', isVegetarian:false, isSpicy:false, spiceLevel:1, allergens:['dairy','shellfish'], tags:[], isBuffetItem:false }),

  // ── INDIAN BREADS ──────────────────────────────────────────────────
  item({ id:'naan', name:'Naan', description:'Classic soft leavened flatbread baked in a tandoor.', price:399, category:'breads', subcategory:'veg', isVegetarian:true, isSpicy:false, spiceLevel:1, allergens:['gluten','dairy'], tags:[], isBuffetItem:true }),
  item({ id:'butter-naan', name:'Butter Naan', description:'Soft naan brushed with butter straight from the tandoor.', price:399, category:'breads', subcategory:'veg', isVegetarian:true, isSpicy:false, spiceLevel:1, allergens:['gluten','dairy'], tags:['bestseller'], isBuffetItem:true }),
  item({ id:'garlic-naan', name:'Garlic Naan', description:'Tandoor-baked naan topped with fresh garlic and butter.', price:499, category:'breads', subcategory:'veg', isVegetarian:true, isSpicy:false, spiceLevel:1, allergens:['gluten','dairy'], tags:['bestseller'], isBuffetItem:true }),
  item({ id:'onion-garlic-naan', name:'Onion Garlic Naan', description:'Naan stuffed and topped with caramelized onions and garlic.', price:499, category:'breads', subcategory:'veg', isVegetarian:true, isSpicy:false, spiceLevel:1, allergens:['gluten','dairy'], tags:[], isBuffetItem:false }),
  item({ id:'roti', name:'Roti', description:'Thin whole-wheat flatbread baked in a tandoor.', price:299, category:'breads', subcategory:'veg', isVegetarian:true, isSpicy:false, spiceLevel:1, allergens:['gluten'], tags:[], isBuffetItem:true }),
  item({ id:'chapati', name:'Chapati', description:'Soft unleavened whole-wheat flatbread cooked on a tawa.', price:299, category:'breads', subcategory:'veg', isVegetarian:true, isSpicy:false, spiceLevel:1, allergens:['gluten'], tags:[], isBuffetItem:true }),
  item({ id:'aloo-paratha', name:'Aloo Paratha', description:'Flaky whole-wheat bread stuffed with spiced mashed potato.', price:499, category:'breads', subcategory:'veg', isVegetarian:true, isSpicy:false, spiceLevel:1, allergens:['gluten'], tags:['bestseller'], isBuffetItem:false }),

  // ── SOUPS AND SALADS ───────────────────────────────────────────────
  item({ id:'daal-soup', name:'Daal Soup', description:'A perfect blend of healthy lentils and fresh vegetables, served with a delicious dressing.', price:699, category:'soups-salads', subcategory:'veg', isVegetarian:true, isSpicy:false, spiceLevel:1, allergens:[], tags:[], isBuffetItem:false }),
  item({ id:'mixed-house-salad', name:'Mixed House Salad', description:'A refreshing mix of crisp greens, juicy tomatoes, crunchy cucumbers and more, topped with your favorite dressing.', price:699, category:'soups-salads', subcategory:'veg', isVegetarian:true, isSpicy:false, spiceLevel:1, allergens:[], tags:[], isBuffetItem:false }),
  item({ id:'mulligatawny-soup', name:'Mulligatawny Soup', description:'A fragrant and flavorful soup, made with Indian spices and coconut milk.', price:799, category:'soups-salads', subcategory:'veg', isVegetarian:true, isSpicy:false, spiceLevel:1, allergens:['nuts'], tags:[], isBuffetItem:false }),
  item({ id:'chicken-soup', name:'Chicken Soup', description:'Soup made from chicken, simmered in water with vegetables and spices.', price:799, category:'soups-salads', subcategory:'non-veg', isVegetarian:false, isSpicy:false, spiceLevel:1, allergens:[], tags:[], isBuffetItem:false }),
  item({ id:'chicken-tikka-salad', name:'Chicken Tikka Salad', description:'Juicy and tender grilled chicken, paired with fresh greens, crispy veggies and a zesty dressing.', price:999, category:'soups-salads', subcategory:'non-veg', isVegetarian:false, isSpicy:false, spiceLevel:1, allergens:['dairy'], tags:[], isBuffetItem:false }),

  // ── SHAWARMA ───────────────────────────────────────────────────────
  item({ id:'tandoori-veggie-shawarma', name:'Tandoori Veggie Shawarma', description:'Shawarma prepared in teardrop-shaped bread freshly baked in a tandoor from thin cuts of seasoned and marinated mix veggies.', price:999, category:'shawarma', subcategory:'veg', isVegetarian:true, isSpicy:false, spiceLevel:1, allergens:['gluten'], tags:[], isBuffetItem:false }),
  item({ id:'tandoori-chicken-shawarma', name:'Tandoori Chicken Shawarma', description:'Shawarma prepared in teardrop-shaped bread freshly baked in a tandoor from thin cuts of seasoned and marinated chicken.', price:1099, category:'shawarma', subcategory:'non-veg', isVegetarian:false, isSpicy:false, spiceLevel:1, allergens:['gluten'], tags:['bestseller'], isBuffetItem:false }),
  item({ id:'tandoori-lamb-shawarma', name:'Tandoori Lamb Shawarma', description:'Shawarma prepared in teardrop-shaped bread freshly baked in a tandoor from thin cuts of seasoned and marinated lamb.', price:1199, category:'shawarma', subcategory:'non-veg', isVegetarian:false, isSpicy:false, spiceLevel:1, allergens:['gluten'], tags:[], isBuffetItem:false }),

  // ── CHINESE ────────────────────────────────────────────────────────
  item({ id:'schezwan-veg-fried-rice', name:'Schezwan Vegetable Fried Rice', description:'Wok-tossed rice with vegetables in spicy Schezwan sauce. Add-ons: Egg +$2, Chicken +$2, Fish +$5, Shrimp +$5.', price:1199, category:'chinese', subcategory:'veg', isVegetarian:true, isSpicy:true, spiceLevel:2, allergens:['soy','gluten'], tags:[], isBuffetItem:false }),
  item({ id:'chicken-fried-rice', name:'Chicken Fried Rice', description:'Wok-tossed rice with chicken and vegetables.', price:1399, category:'chinese', subcategory:'non-veg', isVegetarian:false, isSpicy:false, spiceLevel:1, allergens:['soy','gluten'], tags:[], isBuffetItem:true }),

  // ── CHEF SPECIALS ──────────────────────────────────────────────────
  item({ id:'lagan-dum-chicken', name:'Lagan / Dum Chicken', description:'Slow-cooked marinated chicken in cashew and poppy gravy. The chicken is marinated in curd/yogurt and spices and later slow cooked.', price:1599, category:'chef-specials', subcategory:'non-veg', isVegetarian:false, isSpicy:false, spiceLevel:1, allergens:['dairy','nuts'], tags:['signature'], isBuffetItem:true }),
  item({ id:'malai-chicken', name:'Malai Chicken', description:'Malai chicken is a hugely popular dish with cream, cheese-rich, nutty and creamy saffron and spices.', price:1599, category:'chef-specials', subcategory:'non-veg', isVegetarian:false, isSpicy:false, spiceLevel:1, allergens:['dairy'], tags:['bestseller'], isBuffetItem:true }),
  item({ id:'malai-mutton', name:'Malai Mutton', description:'Malai mutton is a hugely popular dish with cream, cheese-rich, nutty and creamy saffron and spices.', price:1799, category:'chef-specials', subcategory:'non-veg', isVegetarian:false, isSpicy:false, spiceLevel:1, allergens:['dairy'], tags:[], isBuffetItem:true }),
  item({ id:'haryali-chicken', name:'Haryali Chicken', description:'Green chicken curry is a popular dish from the region of Hyderabad. This dish is made up of green chilies, green herbs and spices.', price:1599, category:'chef-specials', subcategory:'non-veg', isVegetarian:false, isSpicy:true, spiceLevel:2, allergens:[], tags:[], isBuffetItem:true }),
  item({ id:'mutton-marag', name:'Mutton Marag', description:"Marag is a soup made with tender mutton attached to bones. It's a spicy, rich and refined mutton stew or soup.", price:1799, category:'chef-specials', subcategory:'non-veg', isVegetarian:false, isSpicy:true, spiceLevel:2, allergens:[], tags:['signature'], isBuffetItem:false }),
  item({ id:'mutton-haleem', name:'Mutton Haleem', description:'Haleem is a stew composed of meat, lentils, spices, ghee and pounded wheat made into a thick paste.', price:1999, category:'chef-specials', subcategory:'non-veg', isVegetarian:false, isSpicy:false, spiceLevel:1, allergens:['gluten'], tags:['signature','bestseller'], isBuffetItem:true }),

  // ── WEEKEND SPECIALS ───────────────────────────────────────────────
  item({ id:'chicken-mandi', name:'Chicken Mandi', description:"Mandi is Yemen's national dish, consisting of chicken, fragrant basmati rice and a mixture of various spices.", price:1999, category:'weekend-specials', subcategory:'non-veg', isVegetarian:false, isSpicy:false, spiceLevel:1, allergens:[], tags:['signature'], isBuffetItem:false }),
  item({ id:'mutton-mandi', name:'Mutton Mandi', description:"Mandi is Yemen's national dish, consisting of mutton, fragrant basmati rice and a mixture of various spices.", price:2999, category:'weekend-specials', subcategory:'non-veg', isVegetarian:false, isSpicy:false, spiceLevel:1, allergens:[], tags:['signature'], isBuffetItem:false }),
  item({ id:'paya-nihari', name:'Paya Nihari', description:'Paya Nihari is a stew, usually slow cooked overnight, which consists of goat trotters (Paya), mainly cooked with bone marrow.', price:1799, category:'weekend-specials', subcategory:'non-veg', isVegetarian:false, isSpicy:false, spiceLevel:1, allergens:[], tags:['signature'], isBuffetItem:false }),
  item({ id:'sufiyani-biryani', name:'Sufiyani Biryani', description:'One of the hidden gems of Hyderabadi cuisine. Rich royal biryani prepared with milk, paste of almonds, khoya (mawa) and minimal ghee. No red chilies are used.', price:2299, category:'weekend-specials', subcategory:'non-veg', isVegetarian:false, isSpicy:false, spiceLevel:1, allergens:['dairy','nuts'], tags:['signature'], isBuffetItem:false }),

  // ── DESSERTS ───────────────────────────────────────────────────────
  item({ id:'sunrise-pudding', name:'Sunrise Pudding', description:'A colorful layered pudding dessert with a smooth, creamy finish.', price:699, category:'desserts', subcategory:'veg', isVegetarian:true, isSpicy:false, spiceLevel:1, allergens:['dairy'], tags:[], isBuffetItem:false }),
  item({ id:'kaddu-ki-kheer', name:'Kaddu Ki Kheer', description:'Traditional pumpkin kheer slow-cooked with milk, sugar, and cardamom.', price:699, category:'desserts', subcategory:'veg', isVegetarian:true, isSpicy:false, spiceLevel:1, allergens:['dairy'], tags:[], isBuffetItem:false }),
  item({ id:'kaser-rabdi', name:'Kaser Rabdi', description:'Rich, thickened milk dessert flavored with saffron and nuts.', price:499, category:'desserts', subcategory:'veg', isVegetarian:true, isSpicy:false, spiceLevel:1, allergens:['dairy','nuts'], tags:[], isBuffetItem:false }),
  item({ id:'gulab-jamun', name:'Gulab Jamun', description:'Soft fried milk dumplings soaked in rose-cardamom syrup.', price:499, category:'desserts', subcategory:'veg', isVegetarian:true, isSpicy:false, spiceLevel:1, allergens:['dairy'], tags:['bestseller'], isBuffetItem:false }),
  item({ id:'ras-malai', name:'Ras Malai', description:'Soft cottage cheese patties served in sweetened, saffron-infused milk.', price:499, category:'desserts', subcategory:'veg', isVegetarian:true, isSpicy:false, spiceLevel:1, allergens:['dairy'], tags:[], isBuffetItem:false }),
  item({ id:'mango-malai', name:'Mango Malai', description:'Creamy mango dessert with condensed milk.', price:699, category:'desserts', subcategory:'veg', isVegetarian:true, isSpicy:false, spiceLevel:1, allergens:['dairy'], tags:[], isBuffetItem:true }),

  // ── DRINKS ─────────────────────────────────────────────────────────
  item({ id:'orange-juice', name:'Orange Juice', description:'Fresh orange juice.', price:399, category:'drinks', subcategory:'veg', isVegetarian:true, isSpicy:false, spiceLevel:1, allergens:[], tags:[], isBuffetItem:true }),
  item({ id:'pinacolada', name:'Pinacolada', description:'Tropical pineapple and coconut drink.', price:499, category:'drinks', subcategory:'veg', isVegetarian:true, isSpicy:false, spiceLevel:1, allergens:[], tags:[], isBuffetItem:true }),
  item({ id:'lemonade', name:'Lemonade', description:'House-made lemonade.', price:399, category:'drinks', subcategory:'veg', isVegetarian:true, isSpicy:false, spiceLevel:1, allergens:[], tags:[], isBuffetItem:true }),
  item({ id:'water', name:'Water', description:'Bottled water.', price:199, category:'drinks', subcategory:'veg', isVegetarian:true, isSpicy:false, spiceLevel:1, allergens:[], tags:[], isBuffetItem:true }),
]

export const STATIC_MENU: Omit<MenuItem, 'createdAt' | 'updatedAt'>[] = withMenuImages(RAW_MENU)
